Repository openshift/template-service-broker-operator, pull requests merged in 2018-11, with the labels that each got.

#1 Bring Erik's stuff in
  Dockerfile
  Makefile
  README.md
  ansible.cfg
  archived/example_olm_obj/crd.yaml
  archived/example_olm_obj/csv.yaml
  archived/example_olm_obj/package.yaml
  cr.example.yaml
  crd.yaml
  main.yml
  manual-deprovision.yml
  operator.yaml
  rbac.yaml
  roles/template-service-broker/defaults/main.yml
  roles/template-service-broker/meta/main.yml
  roles/template-service-broker/tasks/main.yml
  roles/template-service-broker/templates/apiserver.clusterrolebinding.yaml
  roles/template-service-broker/templates/apiserver.clusterservicebroker.yaml
  roles/template-service-broker/templates/apiserver.configmap.yaml
  roles/template-service-broker/templates/apiserver.deployment.yaml
  roles/template-service-broker/templates/apiserver.service.yaml
  roles/template-service-broker/templates/apiserver.serviceaccount.yaml
  roles/template-service-broker/templates/auth-delegator.clusterrolebinding.yaml
  roles/template-service-broker/templates/auth-reader.rolebinding.yaml
  roles/template-service-broker/templates/catalog-auth.role.yaml
  roles/template-service-broker/templates/catalog-auth.rolebinding.yaml
  roles/template-service-broker/templates/templateservicebrokerconfig.yaml
  roles/template-service-broker/templates/tsb-client.clusterrolebinding.yaml
  roles/template-service-broker/templates/tsb-client.secret.yaml
  roles/template-service-broker/templates/tsb-client.serviceaccount.yaml
  roles/template-service-broker/vars/main.yml
  watches.yaml
Labels: size/L

#3 add lint test
  Dockerfile
  Makefile
Labels: size/XS

#4 Update lint test
  Dockerfile
  Makefile
  roles/template-service-broker/handlers/main.yml
  roles/template-service-broker/tasks/main.yml
Labels: lgtm, size/M

#5 fix Makefile .PHONY
  Makefile
Labels: size/XS

#7 Fix operator lint and add OWNERS
  Makefile
  OWNERS
Labels: size/S

#9 Operator should use meta from AO
  main.yml
Labels: approved, lgtm, size/XS
