Repository openshift/template-service-broker-operator, pull requests merged in 2019-06, with the labels that each got.

#44 Bug 1717623 - 4.1.0 -> 4.1.1
  deploy/olm-catalog/openshift-template-service-broker-manifests/4.1/openshifttemplateservicebrokeroperator.v4.1.0.clusterserviceversion.yaml
  deploy/olm-catalog/openshift-template-service-broker-manifests/openshifttemplateservicebroker.package.yaml
  molecule/cluster-olm/prepare.yml
Labels: approved, lgtm, size/XS

#45 Bug 1717623 - 4.1.1 -> 4.1.2
  deploy/olm-catalog/openshift-template-service-broker-manifests/4.1/openshifttemplateservicebrokeroperator.v4.1.0.clusterserviceversion.yaml
  deploy/olm-catalog/openshift-template-service-broker-manifests/openshifttemplateservicebroker.package.yaml
  molecule/cluster-olm/prepare.yml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#46 adding art replacement file
  deploy/olm-catalog/openshift-template-service-broker-manifests/art.yaml
Labels: approved, lgtm, size/S

#47 Fixing ART replacement typo
  deploy/olm-catalog/openshift-template-service-broker-manifests/art.yaml
Labels: approved, lgtm, size/XS

#48 Bug 1721161: cherry-pick adding art yaml file
  deploy/olm-catalog/openshift-template-service-broker-manifests/art.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#49 Adding ability to remove cluster scoped resources on deletion
  watches.yaml
Labels: approved, lgtm, size/XS
