Repository openshift/template-service-broker-operator, pull requests merged in 2019-05, with the labels that each got.

#37 fixing TSB CI
  build/Dockerfile
  deploy/testing/role.yaml.j2
  deploy/testing/role_binding.yaml.j2
  roles/template-service-broker/templates/apiserver.clusterrole.yaml
Labels: approved, lgtm, size/M

#38 Install kubectl so logs can be gathered
  build/custom-ci-build-root.Dockerfile
Labels: approved, lgtm, size/XS

#39 Remove eriknelson from owners file
  OWNERS
Labels: approved, lgtm, size/XS

#40 Don't delete service catalog on destroy step
  molecule/cluster-olm/destroy.yml
Labels: approved, lgtm, size/S

#41 Add image references and fix CI
  deploy/olm-catalog/openshift-template-service-broker-manifests/4.1/image-references
  molecule/cluster-olm/destroy.yml
Labels: approved, lgtm, size/M

#43 Bug 1707324 - fixing permissions for cluster role
  deploy/olm-catalog/openshift-template-service-broker-manifests/4.1/openshifttemplateservicebrokeroperator.v4.1.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS
