Repository openshift/template-service-broker-operator, pull requests merged in 2019-01, with the labels that each got.

#13 Update operator Dockerfile to use AO master, add subresource in CRD
  Dockerfile
  crd.yaml
Labels: approved, lgtm, size/XS

#14 Check for truthy since these values are always defined
  main.yml
Labels: approved, lgtm, size/XS

#16 Add csv.yaml
  olm-catalog/template-service-broker-operator.csv.yaml
Labels: approved, lgtm, size/L

#17 Add installModes
  olm-catalog/template-service-broker-operator.csv.yaml
Labels: approved, lgtm, size/S

#18 Put all the olm bits in olm-catalog
  deploy/olm-catalog/0.1.0/templateservicebroker.crd.yaml
  deploy/olm-catalog/0.1.0/templateservicebrokeroperator.v0.1.0.clusterserviceversion.yaml
  deploy/olm-catalog/templateservicebroker.package.yaml
Labels: approved, lgtm, size/S

#19 Operator SDK Alignment
  Dockerfile.ocp
  Makefile
  README.md
  ansible.cfg
  archived/example_olm_obj/crd.yaml
  archived/example_olm_obj/csv.yaml
  archived/example_olm_obj/package.yaml
  build/Dockerfile
  cr.example.yaml
  deploy/crds/osb_v1alpha1_templateservicebroker_cr.yaml
  deploy/crds/osb_v1alpha1_templateservicebroker_crd.yaml
  deploy/namespace.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  manual-deprovision.yml
  operator.yaml
  playbook.yaml
  rbac.yaml
  roles/template-service-broker/templates/apiserver.clusterrolebinding.yaml
  roles/template-service-broker/templates/apiserver.serviceaccount.yaml
  roles/template-service-broker/templates/auth-delegator.clusterrolebinding.yaml
  roles/template-service-broker/templates/auth-reader.rolebinding.yaml
  roles/template-service-broker/templates/catalog-auth.role.yaml
  roles/template-service-broker/templates/catalog-auth.rolebinding.yaml
  roles/template-service-broker/templates/tsb-client.clusterrolebinding.yaml
  roles/template-service-broker/templates/tsb-client.serviceaccount.yaml
  watches.yaml
Labels: approved, lgtm, size/XL

#20 Update TSBO to own the applications permissions
  deploy/olm-catalog/0.1.0/templateservicebrokeroperator.v0.1.0.clusterserviceversion.yaml
  roles/template-service-broker/defaults/main.yml
  roles/template-service-broker/tasks/main.yml
  roles/template-service-broker/templates/apiserver.clusterrole.yaml
  roles/template-service-broker/templates/apiserver.clusterrolebinding.yaml
  roles/template-service-broker/templates/apiserver.clusterservicebroker.yaml
  roles/template-service-broker/templates/apiserver.deployment.yaml
  roles/template-service-broker/templates/apiserver.serviceaccount.yaml
  roles/template-service-broker/templates/tsb-client.clusterrole.yaml
  roles/template-service-broker/templates/tsb-client.clusterrolebinding.yaml
  roles/template-service-broker/templates/tsb-client.secret.yaml
  roles/template-service-broker/templates/tsb-client.serviceaccount.yaml
  watches.yaml
Labels: approved, lgtm, size/L

#21 Bump csv version
  deploy/olm-catalog/0.2.0/templateservicebroker.crd.yaml
  deploy/olm-catalog/0.2.0/templateservicebrokeroperator.v0.2.0.clusterserviceversion.yaml
  deploy/olm-catalog/templateservicebroker.package.yaml
  roles/template-service-broker/tasks/main.yml
  roles/template-service-broker/templates/apiserver-service-ca-bundle.configmap.yaml
  roles/template-service-broker/templates/apiserver.clusterservicebroker.yaml
Labels: approved, size/M
