Repository openshift/template-service-broker-operator, pull requests merged in 2019-11, with the labels that each got.

#58 Add alert to fire when broker is installed.
  build/Dockerfile
  deploy/olm-catalog/openshift-template-service-broker-manifests/4.3/image-references
  deploy/olm-catalog/openshift-template-service-broker-manifests/4.3/openshifttemplateservicebrokeroperator.v4.3.0.clusterserviceversion.yaml
  deploy/olm-catalog/openshift-template-service-broker-manifests/4.3/templateservicebroker.crd.yaml
  deploy/olm-catalog/openshift-template-service-broker-manifests/art.yaml
  deploy/olm-catalog/openshift-template-service-broker-manifests/openshifttemplateservicebroker.package.yaml
  deploy/role.yaml
  deploy/testing/role.yaml.j2
  molecule/cluster-olm/molecule.yml
  molecule/cluster-olm/prepare.yml
  molecule/cluster/verify.yml
  roles/template-service-broker/tasks/main.yml
  roles/template-service-broker/templates/tsb.prometheus-alert.yaml
Labels: approved, lgtm, size/L

#60 remove the extra brackets to fix the lexer
  build/Dockerfile
  molecule/cluster/verify.yml
Labels: approved, lgtm, size/S

#61 Bug 1772392: Add olm.skipRange to all CSVs and art.yaml
  deploy/olm-catalog/openshift-template-service-broker-manifests/4.1/openshifttemplateservicebrokeroperator.v4.1.0.clusterserviceversion.yaml
  deploy/olm-catalog/openshift-template-service-broker-manifests/4.2/openshifttemplateservicebrokeroperator.v4.2.0.clusterserviceversion.yaml
  deploy/olm-catalog/openshift-template-service-broker-manifests/4.3/openshifttemplateservicebrokeroperator.v4.3.0.clusterserviceversion.yaml
  deploy/olm-catalog/openshift-template-service-broker-manifests/art.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS
