Repository openshift/template-service-broker-operator, pull requests merged in 2019-04, with the labels that each got.

#27 bz1689788 - update imagePullPolicy Always to ifNotPresent
  deploy/olm-catalog/openshift-template-service-broker-manifests/1.0.0/openshifttemplateservicebrokeroperator.v1.0.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#28 Bumping to version 1.0
  Makefile
  build/olm-testing.downstream.Dockerfile
  deploy/crds/osb_v1_templateservicebroker_cr.yaml
  deploy/crds/osb_v1_templateservicebroker_crd.yaml
  deploy/olm-catalog/openshift-template-service-broker-manifests/4.1/openshifttemplateservicebrokeroperator.v4.1.0.clusterserviceversion.yaml
  deploy/olm-catalog/openshift-template-service-broker-manifests/4.1/templateservicebroker.crd.yaml
  deploy/olm-catalog/openshift-template-service-broker-manifests/openshifttemplateservicebroker.package.yaml
  deploy/olm-catalog/templateservicebroker-manifests/0.2.0/templateservicebroker.crd.yaml
  deploy/olm-catalog/templateservicebroker-manifests/0.2.0/templateservicebrokeroperator.v0.2.0.clusterserviceversion.yaml
  watches.yaml
Labels: approved, size/M

#31 Fix version bounds
  build/custom-ci-build-root.Dockerfile
Labels: approved, lgtm, size/XS

#32 Make ansible-lint succeed
  roles/template-service-broker/handlers/main.yml
  roles/template-service-broker/meta/main.yml
  roles/template-service-broker/tasks/main.yml
Labels: approved, lgtm, size/S

#33 Dependencies are all messed up
  build/custom-ci-build-root.Dockerfile
Labels: approved, lgtm, size/XS

#34 wait for CRD to be created, load deployment as file when grabbing logs
  molecule/cluster-olm/playbook.yml
  molecule/cluster-olm/prepare.yml
  molecule/cluster/playbook.yml
  molecule/cluster/verify.yml
Labels: approved, lgtm, size/S

#35 Wait 1 minute instead of looking at api_groups
  molecule/cluster-olm/prepare.yml
Labels: approved, lgtm, size/XS

#36 Properly grab logs, get rid of admin CRB
  molecule/cluster-olm/create.yml
  molecule/cluster-olm/playbook.yml
  molecule/cluster/playbook.yml
Labels: approved, lgtm, size/S
