Repository openshift/template-service-broker-operator, pull requests merged in 2020-05, with the labels that each got.

#71 Bug 1800707: pin CI dependencies
  build/custom-ci-build-root.Dockerfile
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#72 Bug 1800710: pin CI dependencies
  build/custom-ci-build-root.Dockerfile
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#100 Bug 1772743: Add olm.skipRange to all CSVs and art.yaml
  deploy/olm-catalog/openshift-template-service-broker-manifests/4.1/openshifttemplateservicebrokeroperator.v4.1.0.clusterserviceversion.yaml
  deploy/olm-catalog/openshift-template-service-broker-manifests/4.2/openshifttemplateservicebrokeroperator.v4.2.0.clusterserviceversion.yaml
  deploy/olm-catalog/openshift-template-service-broker-manifests/art.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#101 Bug 1782061: Allow the PrometheusAlert to fire.
  deploy/namespace.yaml
  deploy/olm-catalog/openshift-template-service-broker-manifests/4.3/openshifttemplateservicebrokeroperator.v4.3.0.clusterserviceversion.yaml
  deploy/olm-catalog/openshift-template-service-broker-manifests/4.4/openshifttemplateservicebrokeroperator.v4.4.0.clusterserviceversion.yaml
  deploy/role.yaml
  deploy/testing/role.yaml.j2
  deploy/testing/role_binding.yaml.j2
  roles/template-service-broker/defaults/main.yml
  roles/template-service-broker/tasks/main.yml
  roles/template-service-broker/templates/tsb-operator.monitor-role.yaml
  roles/template-service-broker/templates/tsb-operator.monitor-rolebinding.yaml
  roles/template-service-broker/templates/tsb-operator.service-monitor.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#102 Bug 1776133: Allow the PrometheusAlert to fire.
  deploy/namespace.yaml
  deploy/olm-catalog/openshift-template-service-broker-manifests/4.3/openshifttemplateservicebrokeroperator.v4.3.0.clusterserviceversion.yaml
  deploy/role.yaml
  deploy/testing/role.yaml.j2
  deploy/testing/role_binding.yaml.j2
  roles/template-service-broker/defaults/main.yml
  roles/template-service-broker/tasks/main.yml
  roles/template-service-broker/templates/tsb-operator.monitor-role.yaml
  roles/template-service-broker/templates/tsb-operator.monitor-rolebinding.yaml
  roles/template-service-broker/templates/tsb-operator.service-monitor.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm
